# Publish a Docker image to Google Container Registry.
#
# Assumed to run as a subworkflow of .github/workflows/release.yml; specifically, as a publish job
# within `cargo-dist`.
name: "[ruff] Publish Docker image"

on:
  workflow_call:
    inputs:
      plan:
        required: true
        type: string

jobs:
  docker-publish:
    name: Push Docker image ghcr.io/astral-sh/ruff
    runs-on: ubuntu-latest
    environment:
      name: release
    permissions:
      # For the `docker push`.
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/astral-sh/ruff

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: docker
          path: artifact.tar

      - name: Load artifact
        run: docker load -i artifact.tar

      - name: Tag image
        run: docker tag ghcr.io/astral-sh/ruff:latest ghcr.io/astral-sh/ruff:${{ fromJson(inputs.plan).tag || 'dry-run' }}

      - name: Label image
        run: docker label set ${{ steps.meta.outputs.labels }} ghcr.io/astral-sh/ruff:${{ fromJson(inputs.plan).tag || 'dry-run' }}

      - name: Push image
        run: docker push ghcr.io/astral-sh/ruff:${{ fromJson(inputs.plan).tag || 'dry-run' }}
