# Notifies downstream repositories of a new release.
name: NotifyDependents

on:
  workflow_call:
    inputs:
      plan:
        required: true
        type: string

jobs:
  update-dependents:
    name: Update dependents
    runs-on: ubuntu-latest
    needs: publish-release
    steps:
      - name: "Update pre-commit mirror"
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.RUFF_PRE_COMMIT_PAT }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'astral-sh',
              repo: 'ruff-pre-commit',
              workflow_id: 'main.yml',
              ref: 'main',
            })
